### ISSUE TITLE
Is it support Typescript?

### ISSUE THREAD

**Issue by haroldxing** [FrominXu/postmessagejs#1]
I can't find `@types/postmessage-promise` or something

**Comment by FrominXu** [comment]
there is no types-desc file for this libaray's api is simple. But as you metioned, I will add a d.ts file for postmessage-promise package.

**Comment by FrominXu** [comment]
> I can't find `@types/postmessage-promise` or something

TS supported at v2.0.1, with .d.ts in postmessage-promise
