### ISSUE TITLE
按照你教程走的，永远都链接不上，iframe 都生成了，就是链接不上。 版本    "postmessage-promise": "^3.1.1",

### ISSUE THREAD

**Issue by Leozhangshouhai** [FrominXu/postmessagejs#3]
![image](https://user-images.githubusercontent.com/23090937/225638280-0ceb3288-9e54-4c6c-8009-0bb8d0b6ec84.png)
完全按照你教程走的。。。。我的天。

**Comment by Leozhangshouhai** [comment]
我的在iframe 上，进行client示例代码 的操作，在parents 进行 server的操作。。。遗憾落泪。。。一直都不行。。 页面中的iframe已经正常渲染了。但是通信不行。看了一堆源码， 没有找到你在哪里做的通信。 postmessage的方法都没看到你有调用。。 只看到有addeventListener 对“message“的监听

**Comment by FrominXu** [comment]
> 我的在iframe 上，进行client示例代码 的操作，在parents 进行 server的操作。。。遗憾落泪。。。一直都不行。。 页面中的iframe已经正常渲染了。但是通信不行。看了一堆源码， 没有找到你在哪里做的通信。 postmessage的方法都没看到你有调用。。 只看到有addeventListener 对“message“的监听

我们有很多地方都是使用的这个库，是能正常使用的。能贴一下代码吗？看看是哪里有问题

**Comment by Leozhangshouhai** [comment]
不好意思，我确实使用错了 有点晕了。。  已经调整好了。 看源码比较多的方法和postmate 一样的用法。。   在npm上的API上说明上，更完善一点就更好了。。 感谢贡献

**Comment by FrominXu** [comment]
> 不好意思，我确实使用错了 有点晕了。。 已经调整好了。 看源码比较多的方法和postmate 一样的用法。。 在npm上的API上说明上，更完善一点就更好了。。 感谢贡献

你好，3.1.2 版本我更新了说明文档，并增加了简化使用示例，希望能有帮助

**Comment by Leozhangshouhai** [comment]
求问一个问题，  初始化成功，也能正常调用，一切通信都是正常的，但是，控制台中会首次 connect的时候会超时。。很迷茫。。但是通信是正常使用的。
![image](https://user-images.githubusercontent.com/23090937/228820268-cd758187-09fa-4a9a-ae7c-c0bdeadf7d45.png)
我将我自己的所有通信事件，注释了，依旧会报这个错。。

**Comment by Leozhangshouhai** [comment]
使用的是 aysnc的 语法糖，和示例一样的
