### ISSUE TITLE
求问一个问题，  初始化成功，也能正常调用，一切通信都是正常的，但是，控制台中会首次 connect的时候会超时。。很迷茫。。但是通信是正常使用的。

### ISSUE THREAD

**Issue by Leozhangshouhai** [FrominXu/postmessagejs#4]
求问一个问题，  初始化成功，也能正常调用，一切通信都是正常的，但是，控制台中会首次 connect的时候会超时。。很迷茫。。但是通信是正常使用的。
![image](https://user-images.githubusercontent.com/23090937/228820268-cd758187-09fa-4a9a-ae7c-c0bdeadf7d45.png)
我将我自己的所有通信事件，注释了，依旧会报这个错。。

_Originally posted by @Leozhangshouhai in https://github.com/FrominXu/postmessagejs/issues/3#issuecomment-1490128184_

**Comment by FrominXu** [comment]
> 

这个是正常情况，因为原本postMessage是单向的。client端在call服务端时，会用定时器不断发送连接请求（为了尽可能早地建立连接），直到其中的一个通过3次握手与服务端连接成功。因为一个startListening只能建立一个信道，所以那些没有连通的call就会超时。
不过这个报错情况是可以通过条件判断来优化的，等有时间了再来处理，目前应该不阻碍功能吧。
感谢反馈~~

**Comment by Leozhangshouhai** [comment]
目前不影响功能，就是在排查看为啥在报错，感谢大佬
