### ISSUE TITLE
作者什么时候支持一下浏览器 <script> 引入方式？ 

### ISSUE THREAD

**Issue by 15678871232** [FrominXu/postmessagejs#6]
作者什么时候支持一下浏览器 <script> 引入方式？

**Comment by shenxxu720** [comment]
是的，很需要

**Comment by FrominXu** [comment]
> 是的，很需要

需要构建成umd资源，不知道你们是想从哪里来拉取这个资源呢？

**Comment by shenxxu720** [comment]
用于html页面上

**Comment by shenxxu720** [comment]
> > 是的，很需要
> 
> 需要构建成umd资源，不知道你们是想从哪里来拉取这个资源呢？

用于html页面上，html需要通过script标签引入

**Comment by FrominXu** [comment]
> > > 是的，很需要
> > 
> > 
> > 需要构建成umd资源，不知道你们是想从哪里来拉取这个资源呢？
> 
> 用于html页面上，html需要通过script标签引入

我知道是这样用，我的意思这个资源是从哪个域名去取？或者说，你们具体期望的是提供什么样结构的npm包？

**Comment by shenxxu720** [comment]
> > > > 是的，很需要
> > > 
> > > 
> > > 需要构建成umd资源，不知道你们是想从哪里来拉取这个资源呢？
> > 
> > 
> > 用于html页面上，html需要通过script标签引入
> 
> 我知道是这样用，我的意思这个资源是从哪个域名去取？或者说，你们具体期望的是提供什么样结构的npm包？

https://github.com/dollarshaveclub/postmate/blob/master/build/postmate.min.js   像这种的

**Comment by FrominXu** [comment]
已添加 @15678871232 @shenxxu720

**Comment by shenxxu720** [comment]
> 已添加 @15678871232 @shenxxu720

非常感谢
