### ISSUE TITLE
销毁实例后抛出多个postMessage timeout错误

### ISSUE THREAD

**Issue by jy02534655** [FrominXu/postmessagejs#7]
版本为3.2.1，在vue2.7.16中
我创建一个列表iframe，里面使用 callServer 来传值，然后在列表里面有个详情按钮，我点详情按钮的时候会通过postMessage传递消息给列表iframe的容器，这个时候会创建一个弹窗，弹窗里面有一个详情iframe，也是使用callServer 传值，然后再关闭弹窗的时候调用了destroy，日志里面也输出了server closed.按理说不应该抛出postMessage timeout错误，不知道为什么，是销毁不完全吗？

**Comment by FrominXu** [comment]
postMessage timeout 只有在发送过postmessage后没有response响应时出现。你检查下是否有这种情况。不行就请提供个可复现的 https://codesandbox.io/ 示例吧

**Comment by jy02534655** [comment]
> postMessage timeout 只有在发送过postmessage后没有response响应时出现。你检查下是否有这种情况。不行就请提供个可复现的 https://codesandbox.io/ 示例吧

感谢，手动response后解决问题
